### ISSUE TITLE
Can we make `+stable` resolve to the specific version number?

### ISSUE THREAD

**Issue by wookayin** [tweekmonster/helpful.vim#11]
As of today, neovim stable release is 0.8.0 and nightly is 0.9.0-dev.

However, the new APIs that were introduced in the latest stable version (e.g. 0.8.0) but not in the predecessor version (e.g. 0.7.0) are tagged as `+stable` instead of the specific version. This can be very confusing and less useful for the main purpose `helpful.vim`, than specific version numbers where APIs are being newly introduced.

For instance:

```
vim.lsp.util.show_document() | neovim: +nightly
```

This is OK because it says it is 'nightly', but the following may be a bit confusing:

```
vim.deprecate() | neovim: +stable
```

It is not obvious the `+stable` version actually means v0.8.0 (or v.0.8.1, for instance). I guess this entry will be replaced with `v0.8.0` only after `v0.9.0` becomes a new stable version in the future. It would be even better if instead of `+stable`, this resolves to `v0.8.0`.

**Comment by Shougo** [comment]
The Pull Request is wellcome.

**Comment by Shougo** [comment]
I have fixed it.  The tags will be updated in the tomorrow.

**Comment by wookayin** [comment]
Thank you, works perfectly as expected: Now the tag shows `v0.8.0`.
