### ISSUE TITLE
Error invalid character class when using `ctrl-\`

### ISSUE THREAD

**Issue by bruhtus** [tweekmonster/helpful.vim#14]
When i want to look the version when `i_CTRL-\_CTRL-O` appear, i got this error message:
```vim
Error detected while processing function helpful#lookup:
line    6:
E877: (NFA regexp) Invalid character class: 67
```

Step to reproduce:
- Load `helpful.vim` plugin.
- Run `:HelpfulVersion i_CTRL-\_CTRL-O`

That's not only happen with `i_CTRL-\_CTRL-O` but also `c_CTRL-\_e` and i suspect anything that has `CTRL-\` in it or maybe character `\` in general. I haven't noticed an error when using another special character so i'm not sure if it's only with backslash or not.

I've tried to escape the backslash like this `i_CTRL-\\_CTRL-O` and it works as expected.

Maybe we need to add escape for the character backslash, like this?
```vim
...

command! -nargs=+ -complete=help HelpfulVersion call helpful#lookup(escape(<q-args>, '\'))
```

I'm not sure how this works, so i'm reporting this error here first. Thank you!

**Comment by Shougo** [comment]
Fixed.
