### ISSUE TITLE
Please update data for neovim 0.5+

### ISSUE THREAD

**Issue by wookayin** [tweekmonster/helpful.vim#7]
Is this still being maintained? I guess data generation is manual done by @tweekmonster yourself; would you consider automatically generating the tags it through Github actions?

Neovim 0.5.0 was released in July 2021 and the latest data as of today (Oct 21) was generated in June 2021 (out-of-date). Therefore all vim LSP-related data are shown as `neovim +nightly` (should be `neovim +0.5.0` since the stable release). It would be greatly appreciated if you can update the data with the recent versions of neovim and vim 8.2. Thanks.

**Comment by Shougo** [comment]
> Is this still being maintained?

Yes.  I am the maintainer.

Hm... The data should be updated automatically...

I will check it.

**Comment by Shougo** [comment]
@tweekmonster Can you setup github Actions?  It must be setup by repository owner.

**Comment by Shougo** [comment]
The PR exists.  I will merge it later.

**Comment by Shougo** [comment]
@wookayin I have updated data to the latest and merged github actions PR.
Can you check it?

**Comment by wookayin** [comment]
@Shougo Thanks! I can see Github action was set in #6, and the data is now up-to-date.
